Свойство 1

In [2]:
import numpy as np
A = np.matrix("1 2 3; 4 5 6")
print(A)
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


Свойство 2

In [4]:
A = np.matrix("1 2 3; 4 5 6")
B = np.matrix("7 8 9; 0 7 5")
L = (A + B).T
R = A.T + B.T
print(L)
print(R)

[[ 8  4]
 [10 12]
 [12 11]]
[[ 8  4]
 [10 12]
 [12 11]]


Свойство 3

In [5]:
A = np.matrix("1 2; 3 4")
B = np.matrix("5 6; 7 8")
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


Свойство 4

In [6]:
A = np.matrix("1 2 3; 4 5 6")
k = 3
L = (k * A).T
R = k * (A.T)
print(L)
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]
[[ 3 12]
 [ 6 15]
 [ 9 18]]


Свойство 5

In [7]:
A = np.matrix("1 2; 3 4")
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, ".9g"))
print(format(A_T_det, ".9g"))

-2
-2


Действия над матрицами
Свойство 1

In [8]:
A = np.matrix("1 2; 3 4")
L = 1*A
R = A
print(L)
print(R)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


Свойство 2

In [9]:
A = np.matrix("1 2; 3 4")
Z = np.matrix("0 0; 0 0")
L = 0*A
R = Z
print(L)
print(R)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


Свойство 3

In [10]:
A = np.matrix("1 2; 3 4")
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[ 5 10]
 [15 20]]
[[ 5 10]
 [15 20]]


Свойство 4

In [11]:
A = np.matrix("1 2; 3 4")
p = 2
q = 3
L = (p*q) * A
R = p * (q * A)
print(L)
print(R)

[[ 6 12]
 [18 24]]
[[ 6 12]
 [18 24]]


Свойство 5

In [12]:
A = np.matrix("1 2; 3 4")
B = np.matrix("5 6; 7 8")
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)
print(R)

[[18 24]
 [30 36]]
[[18 24]
 [30 36]]


Сложение матриц 
Свойство 1

In [13]:
A = np.matrix("1 6 3; 8 2 7")
B = np.matrix(" 8 1 5; 6 9 12")
C = A + B
print(C)

[[ 9  7  8]
 [14 11 19]]


Свойство 2

In [14]:
A = np.matrix("1 2; 3 4")
B = np.matrix("5 6; 7 8")
C = np.matrix("1 7; 9 3")
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[ 7 15]
 [19 15]]
[[ 7 15]
 [19 15]]


Свойство 3

In [15]:
A = np.matrix("1 2; 3 4")
Z = np.matrix("0 0; 0 0")
L = A + (-1)*A
print(L)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


Умножение матриц
Свойство 1

Свойство 2

Свойство 3

Свойство 4

Свойство 5